name: Android CI (no wrapper)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Siapkan Android SDK + commandline tools
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Install komponen SDK yang diperlukan (sesuaikan compileSdk/buildTools di gradle)
      - name: Install SDK components
        run: |
          sdkmanager --install "platform-tools" "platforms;android-35" "build-tools;35.0.0"
          yes | sdkmanager --licenses

      # Jalankan Gradle TANPA wrapper. Action ini mengunduh Gradle 8.7 otomatis.
      - name: Build Debug APK (Gradle 8.7, no wrapper)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7
          arguments: assembleDebug --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
